---
####### look for installed stuff

- name: Detector | Check if nginx is installed
  shell: apt-cache policy nginx | grep Installed | grep -v "(none)"
  register: nginx
  ignore_errors: true
  tags:
    - laravel


- name: Detector | Check if apache2 is installed
  shell: apt-cache policy apache2 | grep Installed | grep -v "(none)"
  register: apache2
  ignore_errors: true
  tags:
    - laravel


########## Start

- name: Laravel | Installing Laravel globally
  command: "{{ composer_executable }} global require 'laravel/installer={{laravel_installer_version}}' creates=/usr/local/share/composer/vendor/bin/laravel"
  environment:
      COMPOSER_HOME: '{{ composer_home }}'
  tags: laravel


#- name: Laravel | Installing Laravel Liferaft globally
#  command: "{{ composer_executable }} global require 'laravel/liferaft={{laravel_liferaft_version}}' creates=/usr/local/share/composer/vendor/bin/liferaft"
#  environment:
#      COMPOSER_HOME: '{{ composer_home }}'
#  tags: laravel

#- name: Laravel | Make Laravel Liferaft executable
#  get_url:
#    url=https://raw.github.com/antonioribeiro/artisan-anywhere/master/artisan.sh
#    dest={{ laravel_artisan_executable }}
#    mode=0775
#  tags: laravel


- name: Laravel | Craft site
  shell: /usr/local/share/composer/vendor/bin/laravel new laravel
    chdir={{ webserver_document_root }}
    creates={{ webserver_document_root }}/{{ laravel_site_folder_name }}
  tags:
    - laravel


- name: Laravel | Artisan Anywhere
  get_url:
    url=https://raw.github.com/antonioribeiro/artisan-anywhere/master/artisan.sh
    dest={{ laravel_artisan_executable }}
    mode=0775
  tags: laravel


# - name: Laravel | Create directory
#   file:
#     state=directory
#     path={{ laravel_document_root }}
#     group={{ root_username }}
#     owner={{ root_username }}
#   tags: laravel

# - name: Laravel | Download git repository
#   git:
#     repo=https://github.com/laravel/laravel.git
#     dest={{ laravel_document_root }}
#   tags: laravel

# - name: Laravel | Run Composer install
#   command:
#     composer --working-dir={{ laravel_document_root }} install
#     creates={{ laravel_document_root }}/vendor/autoload.php
#   register: composerinstall
#   tags: laravel

# - name: Laravel | Run Composer update
#   command:
#     composer --working-dir={{ laravel_document_root }} update
#   when: composerinstall|skipped
#   tags: laravel

# - name: Laravel | Download and install Artisan Anywhere
#   file:
#     path={{ laravel_artisan_executable }}
#     owner={{ root_username }}
#     group={{ root_username }}
#     mode=0755
#   tags: laravel


# ####### Apache 2 configuration

# - name: Laravel | Configure Apache 2 virtualhost - create file
#   template:
#     src=laravel-apache-virtualhost.conf.tpl
#     dest={{ apache2_config_directory }}/sites-available/laravel.conf
#     owner={{ root_username }}
#     group={{ root_username }}
#     mode=0644
#   notify: restart apache2
#   when: apache2.rc == 0 # exists
#   tags:
#     - laravel


# - name: Laravel | Enable Apache 2 laravel.conf site
#   command: a2ensite laravel
#   when: apache2.rc == 0 # exists
#   tags:
#     - laravel


# ####### NGINX configuration

- name: Laravel | Create NGINX site
  command: bash {{ scripts_path }}/serve.sh {{ laravel_site_host_name }} {{ webserver_document_root }}/{{ laravel_site_folder_name }}/public
  when: nginx.rc == 0 # exists
  tags:
    - laravel

- name: Laravel | Set directory permissions
  file:
    path=/usr/local/share/composer/
    owner={{ user_with_sudo_power }}
    group={{ root_username }}
    mode=0775
    state=directory
    recurse=yes
  tags: laravel

- name: Laravel | Set file permissions
  file:
    path=/usr/local/share/composer/vendor/bin/{{ item }}
    owner={{ user_with_sudo_power }}
    group={{ root_username }}
    mode=0775
    state=file
  with_items:
    - ../laravel/installer/laravel
    - ../laravel/liferaft/liferaft
  tags: laravel
