---
####### look for installed stuff

- name: Detector | Check if nginx is installed
  shell: apt-cache policy nginx | grep Installed | grep -v "(none)"
  register: nginx
  ignore_errors: true
  tags: 
    - detectors


- name: Detector | Check if apache2 is installed
  shell: apt-cache policy apache2 | grep Installed | grep -v "(none)"
  register: apache2
  ignore_errors: true
  tags: 
    - detectors


########## Start

- name: Laravel | Create directory 
  file: 
    state=directory
    path={{ laravel_document_root }}
    group={{ root_username }} 
    owner={{ root_username }}
  tags: laravel

- name: Laravel | Download git repository
  git: 
    repo=https://github.com/laravel/laravel.git 
    dest={{ laravel_document_root }}
  tags: laravel

- name: Laravel | Run Composer install
  command: 
    composer --working-dir={{ laravel_document_root }} install
    creates={{ laravel_document_root }}/vendor/autoload.php
  register: composerinstall
  tags: laravel

- name: Laravel | Run Composer update
  command: 
    composer --working-dir={{ laravel_document_root }} update
  when: composerinstall|skipped
  tags: laravel

- name: Laravel | Set directory permissions
  file: 
    path={{ laravel_document_root }}/app/storage
    owner={{ root_username }}
    group={{ webserver_username }}
    mode=0775
    state=directory
    recurse=yes
  tags: laravel

- name: Laravel | Download mod-pagespeed
  get_url: url=https://raw.github.com/antonioribeiro/artisan-anywhere/master/artisan.sh dest={{ laravel_artisan_executable }}
  tags: laravel

- name: Laravel | Download and install Artisan Anywhere
  file: 
    path={{ laravel_artisan_executable }}
    owner={{ root_username }} 
    group={{ root_username }}     
    mode=0755 
  tags: laravel


####### Apache 2 configuration

- name: Laravel | Configure Apache 2 virtualhost - create file
  template: 
    src=laravel-apache-virtualhost.conf.tpl
    dest={{ apache2_config_directory }}/sites-available/laravel.conf
    owner={{ root_username }} 
    group={{ root_username }}     
    mode=0644 
  notify: restart apache2
  when: apache2.rc == 0 # exists
  tags: 
    - laravel
    

- name: Laravel | Configure Apache 2 virtualhost - enable site
  template: 
    src=laravel-apache-virtualhost.conf.tpl
    dest={{ apache2_config_directory }}/sites-available/laravel.conf
    owner={{ root_username }} 
    group={{ root_username }}     
    mode=0644 
  notify: restart apache2
  when: apache2.rc == 0 # exists
  tags: 
    - laravel
    

- name: Laravel | Enable Apache 2 laravel.conf site
  command: a2ensite laravel
  when: apache2.rc == 0 # exists
  tags: 
    - laravel
    

####### Nginx 2 configuration

- name: Laravel | Configure Nginx virtualhost - create file
  template: 
    src=laravel-nginx-virtualhost-conf.tpl
    dest={{ nginx_config_directory }}/sites-available/laravel
    owner={{ root_username }} 
    group={{ root_username }}     
    mode=0644 
  notify: 
    restart nginx
  when: 
    nginx.rc == 0 # exists
  tags: 
    - laravel
    

- name: Laravel | Configure Nginx virtualhost - enable site
  file: 
    state=link 
    src={{ nginx_config_directory }}/sites-available/laravel
    dest={{ nginx_config_directory }}/sites-enabled/laravel
    owner={{ root_username }} 
    group={{ root_username }}
  notify: 
    restart nginx # exists
  when: 
    nginx.rc == 0 # exists
  tags: 
    - laravel
    
