---
# This playbook deploys the whole application stack in this site.

########################################################################################

- name: apply common configuration to all nodes
  hosts: alerj_all_servers
  user: antoniocarlos
  sudo: yes

  roles:
    - common

########################################################################################

- name: install squid
  hosts: alerj_proxy_servers
  user: antoniocarlos
  sudo: yes

  roles:
    - squid

########################################################################################

- name: install apache2 and php5
  hosts: alerj_webservers
  user: antoniocarlos
  sudo: yes
  roles:
    - apache2
    - css-tools
    - redis
    - node.js

########################################################################################

- name: mysql
  hosts: alerj_database_servers
  user: antoniocarlos
  sudo: yes
  roles:
    - mysql
    - postgresql

