---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: alerj
  user: antoniocarlos
  sudo: yes

  roles:
    - common

#- name: configure and deploy the webservers and application code
#  hosts: alerj_webservers
#  user: antoniocarlos
#
#  roles:
#    - apache2
#
#- name: deploy MySQL and configure the databases
#  hosts: alerj_dbservers
#  user: antoniocarlos
#
#  roles:
#    - mysql
