---

#### Running
#
#    ansible-playbook --inventory-file=/var/www/ansible-laravel/hosts /var/www/ansible-laravel/playbook.yml -K

########################################################################################

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  roles:
    - common

########################################################################################

- name: install php
  hosts: php
  sudo: yes

  roles:
    - php

  handlers:
    - name: restart php
      service: name=php5-fpm state=restarted

########################################################################################

- name: install hhvm
  hosts: hhvm
  sudo: yes

  roles:
    - hhvm

########################################################################################

- name: install zsh
  hosts: zsh
  sudo: yes

  roles:
    - zsh

########################################################################################

- name: install composer
  hosts: composer
  sudo: yes

  roles:
    - composer

########################################################################################

- name: install phpunit
  hosts: phpunit
  sudo: yes

  roles:
    - phpunit

########################################################################################

- name: install phpspec
  hosts: phpspec
  sudo: yes

  roles:
    - phpspec

########################################################################################

- name: install codeception
  hosts: codeception
  sudo: yes

  roles:
    - codeception

########################################################################################

- name: install apache2
  hosts: apache2
  sudo: yes

  roles:
    - apache2


########################################################################################

- name: install nginx
  hosts: nginx
  sudo: yes

  roles:
    - nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install memcached
  hosts: memcached
  sudo: yes

  roles:
    - memcached

########################################################################################

- name: install node.js
  hosts: nodejs
  sudo: yes

  roles:
    - nodejs

########################################################################################

- name: install redis
  hosts: redis
  sudo: yes

  roles:
    - redis

########################################################################################

- name: install mysql
  hosts: mysql
  sudo: yes

  roles:
    - mysql

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart mysql
      service: name=mysql state=restarted

########################################################################################

- name: install phpmyadmin
  hosts: phpmyadmin
  sudo: yes

  roles:
    - phpmyadmin

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install postgresql
  hosts: postgresql
  sudo: yes

  roles:
    - postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

########################################################################################

- name: install beanstalkd
  hosts: beanstalkd
  sudo: yes

  roles:
    - beanstalkd

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install supervisor
  hosts: supervisor
  sudo: yes

  roles:
    - supervisor

########################################################################################

- name: install grunt
  hosts: grunt
  sudo: yes

  roles:
    - grunt

########################################################################################

- name: install python-fabric
  hosts: python-fabric
  sudo: yes

  roles:
    - python-fabric

########################################################################################

- name: install docker
  hosts: docker
  sudo: yes

  roles:
    - docker

########################################################################################

- name: install laravel
  hosts: laravel
  sudo: yes

  roles:
    - laravel

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install squid
  hosts: squid
  sudo: yes

  roles:
    - squid

  handlers:
    - name: restart squid
      service: name=squid3 state=restarted

########################################################################################

- name: install xhgui
  hosts: xhgui
  sudo: yes

  roles:
    - xhgui

########################################################################################

- name: create swap memory
  hosts: swap
  sudo: yes

  roles:
    - swap

########################################################################################

- name: install bower
  hosts: bower
  sudo: yes

  roles:
    - bower

########################################################################################

- name: install phantomjs
  hosts: phantomjs
  sudo: yes

  roles:
    - phantomjs

########################################################################################

- name: install bittorrentsync
  hosts: bittorrentsync
  sudo: yes

  roles:
    - bittorrentsync

########################################################################################

- name: install gulp
  hosts: gulp
  sudo: yes

  roles:
    - gulp

########################################################################################

- name: install java
  hosts: java
  sudo: yes

  roles:
    - java

########################################################################################

- name: install selenium
  hosts: selenium
  sudo: yes

  roles:
    - selenium

########################################################################################

- name: install phpcodesniffer
  hosts: phpcodesniffer
  sudo: yes

  roles:
    - phpcodesniffer

