---

#### Todo:
# http://git-legit.org/
#


- name: apply common configuration to all nodes
  accelerate: true
  hosts: all
  sudo: yes

  roles:
    - common

########################################################################################

- name: install php55
  accelerate: true
  hosts: php55
  sudo: yes

  roles:
    - php55

########################################################################################

- name: install composer
  accelerate: true
  hosts: composer
  sudo: yes

  roles:
    - composer

########################################################################################

- name: install phpunit
  accelerate: true
  hosts: phpunit
  sudo: yes

  roles:
    - phpunit

########################################################################################

- name: install apache2
  accelerate: true
  hosts: apache2
  sudo: yes

  roles:
    - apache2

########################################################################################

- name: install memcached
  accelerate: true
  hosts: memcached
  sudo: yes

  roles:
    - memcached

########################################################################################

- name: install node.js
  accelerate: true
  hosts: nodejs
  sudo: yes

  roles:
    - nodejs

########################################################################################

- name: install redis
  accelerate: true
  hosts: redis
  sudo: yes

  roles:
    - redis

########################################################################################

- name: install mysql
  accelerate: true
  hosts: mysql
  sudo: yes

  roles:
    - mysql

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart mysql
      service: name=mysql state=restarted

########################################################################################

- name: install phpmyadmin
  accelerate: true
  hosts: phpmyadmin
  sudo: yes

  roles:
    - phpmyadmin

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

########################################################################################

- name: install postgresql
  accelerate: true
  hosts: postgresql
  sudo: yes

  roles:
    - postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

########################################################################################

- name: install beanstalkd
  accelerate: true
  hosts: beanstalkd
  sudo: yes

  roles:
    - beanstalkd

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

########################################################################################

- name: install grunt
  accelerate: true
  hosts: grunt
  sudo: yes

  roles:
    - grunt

########################################################################################

- name: install python-fabric
  accelerate: true
  hosts: python-fabric
  sudo: yes

  roles:
    - python-fabric

########################################################################################

- name: install docker
  accelerate: true
  hosts: docker
  sudo: yes

  roles:
    - docker

########################################################################################

- name: install laravel
  accelerate: true
  hosts: laravel
  sudo: yes

  roles:
    - laravel

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
