---

#### Running
#
#    ansible-playbook --inventory-file=/var/www/dev-box/hosts /var/www/devbox/playbook.yml -Kk

#### Todo
# http://git-legit.org/
#

########################################################################################

- name: apply common configuration to all nodes
  hosts: all
  become: yes

  roles:
    - common

########################################################################################

- name: install apache2
  hosts: apache2
  become: yes

  roles:
    - apache2


########################################################################################

- name: install beanstalkd
  hosts: beanstalkd
  become: yes

  roles:
    - beanstalkd

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install bittorrentsync
  hosts: bittorrentsync
  become: yes

  roles:
    - bittorrentsync


########################################################################################

- name: install bower
  hosts: bower
  become: yes

  roles:
    - bower


########################################################################################

- name: install blackfireio
  hosts: blackfireio
  become: yes

  roles:
    - blackfireio


########################################################################################

- name: install codeception
  hosts: codeception
  become: yes

  roles:
    - codeception

########################################################################################

- name: install coffee
  hosts: coffee
  become: yes

  roles:
    - coffee

########################################################################################

- name: install composer
  hosts: composer
  become: yes

  roles:
    - composer

########################################################################################

- name: install csstools
  hosts: csstools
  become: yes

  roles:
    - csstools

########################################################################################

- name: install docker
  hosts: docker
  become: yes

  roles:
    - docker

########################################################################################

- name: install dropbox
  hosts: dropbox
  become: yes

  roles:
    - dropbox

########################################################################################

- name: install grunt
  hosts: grunt
  become: yes

  roles:
    - grunt

########################################################################################

- name: install gulp
  hosts: gulp
  become: yes

  roles:
    - gulp

########################################################################################

- name: install hhvm
  hosts: hhvm
  become: yes

  roles:
    - hhvm

########################################################################################

- name: install java
  hosts: java
  become: yes

  roles:
    - java

########################################################################################

- name: install laravel
  hosts: laravel
  become: yes

  roles:
    - laravel

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted


########################################################################################

- name: install letsencrypt
  hosts: letsencrypt
  become: yes

  roles:
    - letsencrypt

########################################################################################

- name: install memcached
  hosts: memcached
  become: yes

  roles:
    - memcached

########################################################################################

- name: install mysql
  hosts: mysql
  become: yes

  roles:
    - mysql

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart mysql
      service: name=mysql state=restarted


########################################################################################

- name: install newrelic
  hosts: newrelic
  become: yes

  roles:
    - newrelic

########################################################################################

- name: install nginx
  hosts: nginx
  become: yes

  roles:
    - nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install node.js
  hosts: nodejs
  become: yes

  roles:
    - nodejs

########################################################################################

- name: install phantomjs
  hosts: phantomjs
  become: yes

  roles:
    - phantomjs

########################################################################################

- name: install php
  hosts: php
  become: yes

  roles:
    - php

  handlers:
    - name: restart php
      service: name=php5-fpm state=restarted

########################################################################################

- name: install phpcodesniffer
  hosts: phpcodesniffer
  become: yes

  roles:
    - phpcodesniffer

########################################################################################

- name: install phpmyadmin
  hosts: phpmyadmin
  become: yes

  roles:
    - phpmyadmin

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install phpcsfixer
  hosts: phpcsfixer
  become: yes

  roles:
    - phpcsfixer

########################################################################################

- name: install phpspec
  hosts: phpspec
  become: yes

  roles:
    - phpspec

########################################################################################

- name: install phpunit
  hosts: phpunit
  become: yes

  roles:
    - phpunit

########################################################################################

- name: install postgresql
  hosts: postgresql
  become: yes

  roles:
    - postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

########################################################################################

- name: install python-fabric
  hosts: python-fabric
  become: yes

  roles:
    - python-fabric

########################################################################################

- name: install redis
  hosts: redis
  become: yes

  roles:
    - redis

########################################################################################

- name: install selenium
  hosts: selenium
  become: yes

  roles:
    - selenium

########################################################################################

- name: install squid
  hosts: squid
  become: yes

  roles:
    - squid

########################################################################################

- name: install supervisor
  hosts: supervisor
  become: yes

  roles:
    - supervisor

########################################################################################

- name: create swap memory
  hosts: swap
  become: yes

  roles:
    - swap

########################################################################################

- name: ufw
  hosts: ufw
  become: yes

  roles:
    - ufw

########################################################################################

- name: install webmin
  hosts: webmin
  become: yes

  roles:
    - webmin

########################################################################################

- name: install xhgui
  hosts: xhgui
  become: yes

  roles:
    - xhgui

########################################################################################

- name: install zsh
  hosts: zsh
  become: yes

  roles:
    - zsh


