---
##################### Apache2 install.

- name: apache2
  action: apt pkg={{ item }} state=latest
  with_items:
     - apache2
     - libapache2-mod-php5
  tags: apache2

##################### Apache2 setup.

- name: enable modules
  command: a2enmod {{item}} creates=/etc/apache2/mods-enabled/{{item}}.load
  with_items:
     - rewrite
     - headers
     - vhost_alias
     - expires
  tags: apache2

- name: Apache | Configuration file for our site
  action: template src=etc-apache2-sites-available-devserver.j2 dest=/etc/apache2/sites-available/devserver
  tags: apache2

- name: Apache | Disable the default site
  action: command a2dissite default
  ignore_errors: True
  tags: apache2

- name: Apache | Enable our new site
  action: command a2ensite devserver
  ignore_errors: True
  tags: apache2

##################### PHP Setup.

- name: PHP | Configuration file, php.ini
  action: template src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  tags: apache2

- name: APC | Cache configuration file, apc.ini
  action: template src=etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/cli/conf.d/apc.ini
  tags: apache2

- name: APC | Cache configuration file, apc.ini
  action: template src=etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/cgi/conf.d/apc.ini
  tags: apache2

# mod_pagespeed is needs apache2.2-common wich conflicts with apache2.2-bin
# 
# - name: PHP | Download mod-pagespeed
#   action: get_url url=https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb dest=/tmp/mod-pagespeed-stable_current_amd64.deb
#   tags: apache2

# - name: PHP | Install mod-pagespeed
#   action: command dpkg -i /tmp/mod-pagespeed-stable_current_amd64.deb
#   tags: apache2

##################### Restart services

- name: Restart Apache
  action: service name=apache2 state=restarted
  tags: apache2
