---
##################### Apache2 install.

- name: apache2
  apt: pkg={{ item }} state=latest
  with_items:
     - apache2
     - libapache2-mod-php5
  tags: apache2

##################### Apache2 setup.

- name: enable modules
  command: 
    a2enmod {{item}} 
    creates={{ apache_config_directory }}/mods-enabled/{{item}}.load
  with_items:
     - rewrite
     - headers
     - vhost_alias
     - expires
  tags: apache2

- name: Apache | Disable the default site
  command: a2dissite default
  ignore_errors: True
  tags: apache2

# - name: Apache | Configuration file for our site
#   template: src=etc-apache2-sites-available-devserver.j2 dest={{ apache_config_directory }}/sites-available/devserver
#   tags: apache2

# - name: Apache | Enable our new site
#   command: a2ensite devserver
#   ignore_errors: True
#   tags: apache2

##################### PHP Setup.

- name: Apache | PHP5 | Configuration file, php.ini
  template: 
    src=../../../global/templates/php/etc-php5-apache2-php-ini.j2 
    dest=/etc/php5/apache2/php.ini
  tags: apache2

- name: Apache | PHP5 | Browsecap configure ini files
  ini_file: 
    dest={{ item }}
    section=browscap
    option=browscap
    value=/etc/php5/browscap.ini
    backup=yes
  with_items:
    - /etc/php5/apache2/php.ini
  tags: apache2

# mod_pagespeed is needs apache2.2-common wich conflicts with apache2.2-bin
# 
# - name: PHP | Download mod-pagespeed
#   get_url: url=https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb dest=/tmp/mod-pagespeed-stable_current_amd64.deb
#   tags: apache2

# - name: PHP | Install mod-pagespeed
#   command: dpkg -i {{ temporary_files_path }}/mod-pagespeed-stable_current_amd64.deb
#   tags: apache2

##################### Restart services

- name: Restart Apache
  service: name=apache2 state=restarted
  tags: apache2
