---

- name: PhantomJS | download phantomjs
  get_url:
    url=https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs_file_name }}.tar.bz2
    dest=/var/tmp/{{ phantomjs_file_name }}.tar.bz2
  tags: phantomjs

- name: PhantomJS | untar phantomjs
  shell:
    chdir=/var/tmp tar xjf {{ phantomjs_file_name }}.tar.bz2
    creates={{ phantomjs_executable }}
  tags: phantomjs

- name: PhantomJS | symlink the phantomjs executable
  file:
    dest={{ phantomjs_executable }}
    src=/var/tmp/{{ phantomjs_file_name }}/bin/phantomjs
    state=link
  tags: phantomjs
