---

- name: HHVM | Installing apt-key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
  tags: hhvm

- name: HHVM | Installing apt package prerequisites
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu {{ ansible_distribution_release }} main' state=present
  register: last_result
  tags: hhvm

- name: hhvm | Install
  apt:
    pkg=hhvm
    state=latest
  tags: hhvm

# - name: hhvm | Install - If you are getting segfaults
#   apt:
#     pkg=hhvm-dbg
#     state=latest
#   tags: hhvm

# - name: hhvm | Install - Living on the edge (rebuilt everyday, unstable)
#   apt:
#     pkg=hhvm-nightly
#     state=latest
#   tags: hhvm

# - name: hhvm | Install - Segfaults in the nightly
#   apt:
#     pkg=hhvm-nightly-dbg
#     state=latest
#   tags: hhvm

