---

- name: PHPUnit | Installing globally
  command: "{{ composer_executable }} global require 'phpunit/phpunit={{phpunit_version}}'"
  environment:
      COMPOSER_HOME: '{{ composer_home }}'
  tags: phpunit
