---

- name: PHPUnit | Create directory
  file: 
    path={{ phpunit_directory }} 
    state=directory 
    owner={{ root_username }} 
    group={{ root_username }} 
    mode=0755
  tags: phpunit

- name: PHPUnit | Create composer.json file
  template: 
    src=composer.json.tpl 
    dest={{ phpunit_directory }}/composer.json
  tags: phpunit

- name: PHPUnit | Running composer update to download sources
  command: composer --working-dir={{ phpunit_directory }} update 
  tags: phpunit

- name: PHPUnit | Set executable bit
  file: 
    path={{ phpunit_directory }}/vendor/phpunit/phpunit/composer/bin/phpunit 
    owner={{ root_username }} 
    group={{ root_username }} 
    mode=0755
  tags: phpunit

# somehow there is already a phpunit dir in /usr/bin, let's remove it

- name: PHPUnit | Put executable in the environment path variable
  shell: rm -rf {{ phpunit_executable }} 
  tags: phpunit

- name: PHPUnit | Put executable in the environment path variable
  file: 
    state=link 
    src={{ phpunit_directory }}/vendor/phpunit/phpunit/composer/bin/phpunit 
    dest={{ phpunit_executable }} 
    owner={{ root_username }} 
    group={{ root_username }}
  tags: phpunit
