---

- name: Composer | Install
  shell:
    cd {{ temporary_files_path }} && curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /tmp/composer.phar {{ composer_executable }}
    creates={{ composer_executable }}
  tags: composer

- name: Composer | Set permissions
  file:
    path={{ composer_executable }}
    owner={{ root_username }}
    group={{ root_username }}
    mode=0755
  tags: composer

- name: Composer | Add Composer to PATH
  template:
    src=composer_path.sh
    dest=/etc/profile.d/composer_path.sh
    mode=0755
  tags: composer

- name: Common | add global update script to cron daily
  template:
    src=composerGlobalUpdate.sh
    dest=/etc/cron.daily/composerGlobalUpdate
    mode=755
  tags: composer

- name: Common | add self update script to cron daily
  template:
    src=composerSelfUpdate.sh
    dest=/etc/cron.daily/composerSelfUpdate
    mode=755
  tags: composer
