---

- name: Composer | Install
  shell:
    cd {{ temporary_files_path }} && curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /tmp/composer.phar {{ composer_executable }}
    creates={{ composer_executable }}
  tags: composer

- name: Composer | Set permissions
  file: 
    path={{ composer_executable }} 
    owner={{ root_username }} 
    group={{ root_username }} 
    mode=0755
  tags: composer
