##
# CSS compiling tools.
#
- name: CSS Tools | Install rubygems package
  apt:
    pkg=rubygems-integration
    state=installed
  tags: csstools

- name: CSS Tools | Install SASS
  command: gem install sass
           creates=/usr/local/bin/sass
  tags: csstools

- name: CSS Tools | Install Susy (no more --pre required as it is 1.0 now)
  command: gem install susy
  tags: csstools

- name: CSS Tools | Install Compass
  command: gem install compass
           creates=/usr/local/bin/compass
  tags: csstools

- name: CSS Tools | Install Aurora (which will install breakpoint, sass-buttons, respond-to)
  command: gem install compass-aurora
  tags: csstools
