---

- name: New Relic | Installing apt-key
  apt_key:
    url=https://download.newrelic.com/548C16BF.gpg
    state=present
  tags: newrelic

- name: New Relic | Add repository
  apt_repository:
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present
    update_cache=yes
  tags: newrelic

- name: New Relic | Install
  apt:
    name=newrelic-sysmond
    state=installed
  tags: newrelic

- name: New Relic | Configure key
  lineinfile: dest=/etc/newrelic/nrsysmond.cfg
    regexp=^license_key=
    line=license_key={{ new_relic_key }}
  tags: newrelic

- name: New Relic | Configure hostname
  lineinfile: dest=/etc/newrelic/nrsysmond.cfg
    regexp='^hostname='
    insertafter='^#hostname='
    line='hostname={{ new_relic_hostname | default(ansible_hostname, True) }}'
  tags: newrelic

- name: New Relic | Restart New Relic
  service:
    name: newrelic-sysmond
    state: restarted
  tags: newrelic

