---

- name: New Relic | Installing apt-key
  apt_key:
    url=https://download.newrelic.com/548C16BF.gpg
    state=present
  tags: newrelic

- name: New Relic | Add repository
  apt_repository:
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present
    update_cache=yes
  tags: newrelic

- name: New Relic | Install
  apt:
    name=newrelic-sysmond
    state=installed
  tags: newrelic

- name: Add New Relic Config
  template:
    src: nrsysmond.cfg.j2
    dest: /etc/newrelic/nrsysmond.cfg
    owner: newrelic
    group: newrelic
  tags: newrelic

- name: Restart New Relic
  service:
    name: newrelic-sysmond
    state: restarted
  tags: newrelic

