---
# This playbook contains common plays that will be run on all nodes.

# sudo apt-get --yes install joe mc links alien apt-file zip vim rsync sudo rdate locate libterm-readkey-perl p7zip-full expect lynx less psmisc nmap lsof socat jfsutils

- name: common packages
  action: apt pkg={{ item }} state=latest
  with_items:
     - joe
     - mc
     - links
     - alien
     - apt-file
     - zip
     - vim
     - rsync
     - sudo
     - rdate
     - locate
     - libterm-readkey-perl
     - p7zip-full
     - expect
     - lynx
     - less
     - psmisc
     - nmap
     - lsof
     - socat
     - jfsutils
     - git
     - bzip2
     - openssl
     - atop
     - python-software-properties
  tags: common

- name: create aliases file
  template: src=aliases.sh dest=/etc/aliases.sh mode=755
  tags: common

- name: create scripts directory.
  file: state=directory path=/etc/scripts group=root owner=root
  tags: common

- name: create add apt repository script
  template: src=add-apt-repository.sh dest=/etc/scripts/add-apt-repository.sh mode=755
  tags: common

- name: create administrator user
  user: name=administrator comment="Administrador ALERJ" uid=9999 password=$system_administrator_password groups=adm,sudo
  tags: common
