---
# This playbook contains common plays that will be run on all nodes.

# sudo apt-get --yes install joe mc links alien apt-file zip vim rsync sudo rdate locate libterm-readkey-perl p7zip-full expect lynx less psmisc nmap lsof socat jfsutils

- name: common packages
  action: apt pkg={{ item }} state=latest
  with_items:
     - joe
     - mc
     - links
     - alien
     - apt-file
     - zip
     - vim
     - rsync
     - sudo
     - rdate
     - locate
     - libterm-readkey-perl
     - p7zip-full
     - expect
     - lynx
     - less
     - psmisc
     - nmap
     - lsof
     - socat
     - jfsutils
     - git
     - bzip2
     - openssl
     - atop
  tags: packages

- name: aliases
  template: src=aliases.sh dest=/etc/aliases.sh
