---
# sudo apt-get --yes install joe mc links alien apt-file zip vim rsync sudo rdate locate libterm-readkey-perl p7zip-full expect lynx less psmisc nmap lsof socat jfsutils

- name: common packages
  apt: pkg={{ item }} state=latest
  with_items:
     - joe
     - mc
     - links
     - alien
     - apt-file
     - zip
     - vim
     - rsync
     - sudo
     - rdate
     - locate
     - libterm-readkey-perl
     - p7zip-full
     - expect
     - lynx
     - less
     - psmisc
     - nmap
     - lsof
     - socat
     - jfsutils
     - git
     - git-core
     - bzip2
     - openssl
     - atop
     - python-software-properties
     - python 
     - python-pip
     - g++ 
     - make
     - tmux
     - irssi
     - build-essential
     - python-dev
     - sshpass
     - subversion
     - telnet
     - debconf-utils
     - tree
     - patch
     - zip
     - unzip 
     - rar
     - libxml2-dev 
     - libxslt-dev
  tags: common

- name: create scripts directory.
  file: 
    state=directory 
    path={{ scripts_path }} 
    group={{ root_username }} 
    owner={{ root_username }}
  tags: common

- name: create aliases file
  template: 
    src=aliases.sh.tpl 
    dest={{ scripts_path }}/aliases.sh 
    mode=755
  tags: common

- name: create administrator user
  user: 
    name={{ system_administrator_name }} 
    comment={{ system_administrator_comment }} 
    uid={{ system_administrator_uid }} 
    password=$system_administrator_password 
    groups=adm,sudo
  when: system_administrator_name != ""
  tags: common
