---
# sudo apt-get --yes install joe mc links alien apt-file zip vim rsync sudo rdate locate libterm-readkey-perl p7zip-full expect lynx less psmisc nmap lsof socat jfsutils

- name: Common | install common packages
  apt: pkg={{ item }} state=latest
  with_items:
     - alien
     - acl
     - apt-file
     - atop
     - build-essential
     - bzip2
     - debconf-utils
     - dnsutils
     - expect
     - g++
     - git
     - git-core
     - irssi
     - jfsutils
     - joe
     - less
     - libterm-readkey-perl
     - libxml2-dev
     - libxslt1-dev
     - links
     - locate
     - lsof
     - lynx
     - make
     - mc
     - nmap
     - openssl
     - p7zip-full
     - patch
     - psmisc
     - python
     - python-apt
     - python-dev
     - python-keyczar
     - python-pip
     - python-pycurl
     - python-software-properties
     - rdate
     - rsync
     - socat
     - sshpass
     - sshpass
     - subversion
     - sudo
     - telnet
     - tmux
     - tree
     - unzip
     - vim
     - zip
     - dos2unix
     - libgnome-keyring-dev
     - smartmontools

  tags: common

- name: install rar
  apt: pkg=rar state=latest
  ignore_errors: true
  tags: common

- name: Common | create scripts directory.
  file:
    state=directory
    path={{ scripts_path }}
    group={{ root_username }}
    owner={{ root_username }}
  tags: common

- name: Common | create aliases file
  template:
    src=aliases.sh.tpl
    dest={{ scripts_path }}/aliases.sh
    mode=755
  tags: common

- name: Common | create sysctl.conf file
  template:
    src=sysctl.conf.j2
    dest=/etc/sysctl.conf
    mode=755
  tags: common

- name: Common | create administrator user
  user:
    name={{ system_administrator_name }}
    comment={{ system_administrator_comment }}
    uid={{ system_administrator_uid }}
    password={{ system_administrator_password }}
    groups=adm,sudo
    state=present
  when: system_administrator_name != ""
  tags: common

- name: Common | compile gnome keyring
  command: /usr/bin/make
    chdir=/usr/share/doc/git/contrib/credential/gnome-keyring
    creates=/usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring.o
  tags: common

- name: Common | Add scripts to PATH
  template:
    src=scripts_path.sh
    dest=/etc/profile.d/scripts_path.sh
    mode=0775
  tags: common
