---

- name: Docker | Install raring kernel image
  apt: 
    pkg={{ item }} 
    state=latest
  with_items:
     - linux-image-generic-lts-raring 
     - linux-headers-generic-lts-raring
  register: reboot_needed
  when: 
    ansible_distribution != "Ubuntu" or 
    ansible_distribution_version < "13.04"
  tags: docker

- name: Docker | Install Linux Extra Image (for 13.04+)
  apt: 
    pkg={{ item }} 
    state=latest
  with_items:
     - linux-image-extra-{{ ansible_kernel }}
  register: reboot_needed
  when: 
    ansible_distribution == "Ubuntu" and
    ansible_distribution_version >= "13.04"
  tags: docker

- name: Docker | Install Linux Containers
  apt: 
    pkg={{ item }} 
    state=latest
  with_items:
     - lxc
  tags: docker
    
# instalation via packages having problems to apt-get update
#
# - name: Docker | Installing apt-key
#   apt_key: url=https://get.docker.io/gpg state=present
#   tags: docker

# - name: Docker | Installing apt package prerequisites
#   apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
#   register: last_result
#   tags: docker

# - name: Docker | Update the apt cache for the new repositories
#   apt: update-cache=yes
#   when: last_result.changed
#   tags: docker

# - name: Docker | Installing packagess
#   apt: pkg={{ item }} state=latest
#   with_items:
#      - lxc-docker
#   tags: docker

- name: Docker | Downloading and Installing
  get_url: 
    dest={{ docker_executable }} 
    url=https://get.docker.io/builds/Linux/x86_64/docker-latest
  tags: docker
 
- name: Docker | Setting up permissions
  file: 
    path={{ docker_executable }} 
    owner={{ root_username }} 
    group={{ root_username }} 
    mode=0755
  tags: docker

- name: Docker | Copy upstart script
  copy: 
    src=docker.upstart
    dest={{ upstart_path }}/docker.conf 
    owner={{ root_username }} 
    group={{ root_username }} 
    mode=0644
  tags: docker

- name: Docker | Check if Linux image has changed and reboot server
  command: $reboot_command
  when: reboot_needed.changed
  tags: docker
