---

##### Console - https://github.com/ptrofimov/beanstalk_console


####### look for installed stuff

- name: Detector | Check if nginx is installed
  shell: apt-cache policy nginx | grep Installed | grep -v "(none)"
  register: nginx
  ignore_errors: true
  tags:
    - beanstalkd


- name: Detector | Check if apache2 is installed
  shell: apt-cache policy apache2 | grep Installed | grep -v "(none)"
  register: apache2
  ignore_errors: true
  tags:
    - beanstalkd


##### Start

- name: Beanstalkd | Install
  apt: pkg={{ item }} state=latest
  with_items:
     - beanstalkd
  tags:
    - beanstalkd


- name: Beanstalkd | Install Console
  git:
    repo=https://github.com/ptrofimov/beanstalk_console.git
    dest={{ webserver_document_root }}/beanstalk_console
    force=yes
  notify:
    restart nginx
  tags: beanstalkd


- name: Beanstalkd | Configure Nginx virtualhost - enable site
  file:
    state=link
    src={{ webserver_document_root }}/beanstalk_console/public
    dest={{ webserver_document_root }}/beanstalk_console/beanstalk
    owner={{ root_username }}
    group={{ root_username }}
  notify:
    restart nginx
  when:
    nginx.rc == 0 # exists
  ignore_errors: True
  tags:
    - beanstalkd


- name: Beanstalkd | Create first server on config.php
  template:
    src=config.php.tpl
    dest={{ webserver_document_root }}/beanstalk_console/config.php
  tags: beanstalkd


- name: Beanstalkd | Set to start on boot
  command: sed -i "s/#START=yes/START=yes/" /etc/default/beanstalkd
  tags: beanstalkd


- name: Beanstalkd | Set directory permissions
  file:
    path={{ webserver_document_root }}/beanstalk_console/
    owner={{ root_username }}
    group={{ root_username }}
    mode=0755
    state=directory
    recurse=yes
  tags: beanstalkd


#### Apache 2

- name: Beanstalkd | Configure Apache virtualhost
  template:
    src=apache2-virtualhost.tpl
    dest={{ apache_config_directory }}/sites-available/beanstalkd-console.conf
    owner={{ root_username }}
    group={{ root_username }}
    mode=0644
  notify: restart apache2
  when:
    apache2.rc == 0 # exists
  tags: beanstalkd

- name: Beanstalkd | Enable beanstalkd-console site
  command: a2ensite beanstalkd-console
  when:
    apache2.rc == 0 # exists
  tags: beanstalkd


#### Nginx

- name: Beanstalkd | Configure Nginx virtualhost
  template:
    src=nginx-virtualhost.tpl
    dest={{ nginx_config_directory }}/locations-available/beanstalkd-console.conf
    owner={{ root_username }}
    group={{ root_username }}
    mode=0644
  notify:
    restart nginx
  when:
    nginx.rc == 0 # exists
  tags:
    - beanstalkd

- name: Beanstalkd | Configure Nginx virtualhost - enable site
  file:
    state=link
    src={{ nginx_config_directory }}/locations-available/beanstalkd-console.conf
    dest={{ nginx_config_directory }}/locations-enabled/beanstalkd-console.conf
    owner={{ root_username }}
    group={{ root_username }}
  notify:
    restart nginx
  when:
    nginx.rc == 0 # exists
  tags:
    - beanstalkd

