---

- name: PHP5.5 | Add Ondrej's PPA for PHP55
  apt_repository: repo='ppa:ondrej/php5'
  register: last_result
  tags: php55

- name: PHP5.5 | Update the apt cache for the new repository
  action: apt update-cache=yes
  when: last_result.changed
  tags: php55

- name: PHP5.5 | Install PHP and all related packages
  action: apt pkg={{ item }} state=latest
  register: result
  with_items:
     - php5
     - php5-cli
     - php-apc
     - php-pear
     - php-xml-parser
     - php5-apcu
     - php5-cgi
     - php5-common
     - php5-curl
     - php5-dev
     - php5-geoip
     - php5-imagick
     - php5-ldap
     - php5-mcrypt
     - php5-memcached
     - php5-pgsql
     - php5-xdebug
     - php5-xmlrpc
     - libmagickwand-dev

  tags: php55

- name: PHP5.5 | Install XDebug
  action: command pecl install xdebug creates=/usr/share/php/.registry/.channel.pecl.php.net/xdebug.reg
  tags: php55

- name: PHP5.5 | Install Imagick
  action: command pecl install imagick creates=/usr/share/php/.registry/.channel.pecl.php.net/imagick.reg
  tags: php55

- name: PHP5.5 | Install memcached
  action: apt pkg=memcached state=latest
  tags: php55
